-- Netflix Project
DROP TABLE NETFLIX
CREATE TABLE NETFLIX
(
	show_id VARCHAR(6),
	type VARCHAR(10),
	title VARCHAR(150),
	director VARCHAR(208),
	castS VARCHAR(1000),
	country VARCHAR(150),
	date_added VARCHAR(50),
	release_year INT,
	rating VARCHAR(10),
	duration  VARCHAR(50),
	listed_in VARCHAR(100),
	description VARCHAR(250)
)
SELECT * FROM NETFLIX;

SELECT COUNT(*) 
FROM NETFLIX

-- 1) FIND THE NO. OF MOVIES VS TV SHOWS

SELECT
	type,
	COUNT(*) AS TOTAL_COUNT
FROM NETFLIX
GROUP BY type;

-- 2) FIND THE TOTAL NO. OF TITLES AVAILABLE ON NETFLIX
SELECT
	COUNT(title)
FROM NETFLIX;

-- 3) DISPLAY ALL MOVIES REEASED AFTER 2020
SELECT *
FROM NETFLIX 
WHERE type = 'Movie' and release_year > 2020;


-- 4) FIMD THE MOST COMMON RATING FOR MOVIES AND TV
SELECT 
	type,
	rating
FROM
	(SELECT 
		type, 
		rating,
		count(*),         
		RANK() OVER(PARTITION BY type ORDER BY COUNT(*) DESC) AS RANKING     
	FROM NETFLIX
	GROUP BY 1, 2) AS T1
WHERE RANKING = 1;

-- 5) LIST ALL MOVIES RELEASED IN SPECIFIC YEAR
SELECT
	type, 
	title
FROM NETFLIX
WHERE release_year = 2000 AND type = 'Movie';

-- 6) FIND THE TOP 5 COUNTRIES WITH MOST CONNTENT ON NETFLIX
SELECT 
	UNNEST(STRING_TO_ARRAY(country, ',')) AS NEW_COUNTRY,
	COUNT(show_id) AS TOTAL_CONTENT
FROM NETFLIX
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;

-- 7) IDENTIFY THE LONGEST MOVIE OR TV SHOW DURATION
SELECT *
FROM NETFLIX
WHERE type = 'Movie' AND duration = (SELECT MAX(duration) FROM NETFLIX);

-- 8) FIND CONTENT ADDED ON LAST 5 YEARS
SELECT *
FROM NETFLIX
WHERE TO_DATE(date_added, 'Month DD, YYYY') >= CURRENT_DATE - INTERVAL '5 YEARS';

-- 9) FIND ALL MOVIES/TV SHOWS BY DIRECTOR 'RAJIV CHILAKA'
SELECT 
	type,
	title,
	director
FROM NETFLIX 
WHERE director ILIKE '%Rajiv Chilaka%';

-- 10) LIST ALL TV SHOWS WITH MORE THAN 5 SEASONS
SELECT *
FROM NETFLIX
WHERE type = 'TV Show' AND SPLIT_PART(duration, ' ', 1)::NUMERIC > 5;

-- 11) COUNT THE NO. OF CONTENT ITEMS IN EACH GENRE
SELECT
	UNNEST(STRING_TO_ARRAY(listed_in, ',')) AS GENRE,
	COUNT(show_id) AS TOTAL_CONTENT
FROM NETFLIX
GROUP BY 1;

-- 12) FIND EACH YEAR AND THE AVERAGE NUMBERS OF CONTENT RELEASE BY INDIA ON
-- NETFLIX . RETUTN TOP 5 YEARS WITH HIGHEST AVERAGE CONTENT RELEASED
SELECT
	EXTRACT(YEAR FROM TO_DATE(date_added, 'Month DD,YYYY')) AS NEW_DATE,
	COUNT(*) AS YEARLY_CONTENT,
	ROUND(
		COUNT(*)::NUMERIC/(SELECT COUNT(*) FROM NETFLIX WHERE country = 'India')::NUMERIC * 100,2)AS AVG_CONTENT
FROM NETFLIX
WHERE country = 'India'
GROUP BY 1
ORDER BY 3 DESC
LIMIT 5;

-- 13) LIST ALL MOVIES THAT ARE DOCUMENTARIES
SELECT *
FROM NETFLIX
WHERE  listed_in ILIKE '%Documentaries%' AND type = 'Movie';


-- 14) FIND ALL CONTENT WITHOUT A DIRECTOR
SELECT *
FROM NETFLIX
WHERE director IS NULL;

-- 15) FIND HOW MANY MOVIES ACTOR 'SALMAN KHAN' APPEARED IN LAST 10 YEARS
SELECT *
FROM NETFLIX 
WHERE castS ILIKE '%Salman khan%' AND release_year > EXTRACT(YEAR FROM CURRENT_DATE) - 10;

--16) FIND THE TOP 10 ACTORS WHO HAVE APPEARED IN HIGHEST NO. OF MOVIES PRODUCED IN INDIA.
SELECT 
	UNNEST(STRING_TO_ARRAY(castS, ',')) AS ACTORS,
	COUNT(*)  AS TOTAL_CONTENT
FROM NETFLIX
WHERE country ILIKE '%india%'
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10;

-- 17) CATEGORIZE THE CONTENT BASED ON THE PRESENCE OF KEYWORDS 'KILL' AND 'VIOLENCE'
--   IN THE DESCRIPTION FEILD. LABEL CONTENT CONTAINING THESE KEYWORDS AS 'BAD' AD ALL 
--   OTHER CONTENT AS 'GOOD'. COUNT HOW MANY ITEMS FALL INTO EACH CAEGORY.
WITH NEW_TABLE
AS(
	SELECT 
		*, 
		CASE 
			WHEN description ILIKE '%Kill%' OR  description ILIKE '%Violence'
			THEN 'BAD CONTENT'
			ELSE 'GOOD CONTENT'
		END CATEGORY
	FROM NETFLIX)
SELECT
	CATEGORY,
	COUNT(*) AS TOTAL_CONTENT
FROM NEW_TABLE
GROUP BY 1;




